version: "3"
services:
  user:
    # replace username/repo:tag with your name and image details
    image: user
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: none
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
